// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvnuyzrhhtjrdykrlasy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2bnV5enJoaHRqcmR5a3JsYXN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NTMxMjIsImV4cCI6MjA2NTAyOTEyMn0.miXzMwC79bQaKBjxt8SHkkysLy9YRMTMWFhkuHmTvug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);